//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsPersonal
    {
        public int id { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public string PhoneNumber { get; set; }
        public int Salary { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual a_Country a_Country { get; set; }
        public virtual EmployeeDetailsOfficial EmployeeDetailsOfficial { get; set; }
    }
}
