//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsOfficial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetailsOfficial()
        {
            this.EmployeeDetailsPersonals = new HashSet<EmployeeDetailsPersonal>();
            this.ModificationInfoes = new HashSet<ModificationInfo>();
            this.ModificationInfoes1 = new HashSet<ModificationInfo>();
            this.RandomKeys = new HashSet<RandomKey>();
        }
    
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public int Designation { get; set; }
        public int DepartmentCode { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public int OfficeCode { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
    
        public virtual a_DepartmentDetails a_DepartmentDetails { get; set; }
        public virtual a_Designation a_Designation { get; set; }
        public virtual a_OfficeDetails a_OfficeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetailsPersonal> EmployeeDetailsPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModificationInfo> ModificationInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModificationInfo> ModificationInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomKey> RandomKeys { get; set; }
    }
}
