//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationInfo
    {
        public int LogNumber { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual EmployeeDetailsOfficial EmployeeDetailsOfficial { get; set; }
        public virtual EmployeeDetailsOfficial EmployeeDetailsOfficial1 { get; set; }
    }
}
